package com.example.test0821.entity;

import java.util.Date;

public class Student {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wn_student.student_id
     *
     * @mbg.generated Mon Aug 24 22:56:34 CST 2020
     */
    private Integer studentId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wn_student.student_name
     *
     * @mbg.generated Mon Aug 24 22:56:34 CST 2020
     */
    private String studentName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wn_student.student_birth
     *
     * @mbg.generated Mon Aug 24 22:56:34 CST 2020
     */
    private String studentBirth;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wn_student.student_status
     *
     * @mbg.generated Mon Aug 24 22:56:34 CST 2020
     */
    private Integer studentStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wn_student.student_regist_time
     *
     * @mbg.generated Mon Aug 24 22:56:34 CST 2020
     */
    private Date studentRegistTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wn_student.student_school
     *
     * @mbg.generated Mon Aug 24 22:56:34 CST 2020
     */
    private String studentSchool;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wn_student.student_major
     *
     * @mbg.generated Mon Aug 24 22:56:34 CST 2020
     */
    private String studentMajor;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column wn_student.student_graduate_time
     *
     * @mbg.generated Mon Aug 24 22:56:34 CST 2020
     */
    private Date studentGraduateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wn_student.student_id
     *
     * @return the value of wn_student.student_id
     *
     * @mbg.generated Mon Aug 24 22:56:34 CST 2020
     */
    public Integer getStudentId() {
        return studentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wn_student.student_id
     *
     * @param studentId the value for wn_student.student_id
     *
     * @mbg.generated Mon Aug 24 22:56:34 CST 2020
     */
    public void setStudentId(Integer studentId) {
        this.studentId = studentId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wn_student.student_name
     *
     * @return the value of wn_student.student_name
     *
     * @mbg.generated Mon Aug 24 22:56:34 CST 2020
     */
    public String getStudentName() {
        return studentName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wn_student.student_name
     *
     * @param studentName the value for wn_student.student_name
     *
     * @mbg.generated Mon Aug 24 22:56:34 CST 2020
     */
    public void setStudentName(String studentName) {
        this.studentName = studentName == null ? null : studentName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wn_student.student_birth
     *
     * @return the value of wn_student.student_birth
     *
     * @mbg.generated Mon Aug 24 22:56:34 CST 2020
     */
    public String getStudentBirth() {
        return studentBirth;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wn_student.student_birth
     *
     * @param studentBirth the value for wn_student.student_birth
     *
     * @mbg.generated Mon Aug 24 22:56:34 CST 2020
     */
    public void setStudentBirth(String studentBirth) {
        this.studentBirth = studentBirth == null ? null : studentBirth.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wn_student.student_status
     *
     * @return the value of wn_student.student_status
     *
     * @mbg.generated Mon Aug 24 22:56:34 CST 2020
     */
    public Integer getStudentStatus() {
        return studentStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wn_student.student_status
     *
     * @param studentStatus the value for wn_student.student_status
     *
     * @mbg.generated Mon Aug 24 22:56:34 CST 2020
     */
    public void setStudentStatus(Integer studentStatus) {
        this.studentStatus = studentStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wn_student.student_regist_time
     *
     * @return the value of wn_student.student_regist_time
     *
     * @mbg.generated Mon Aug 24 22:56:34 CST 2020
     */
    public Date getStudentRegistTime() {
        return studentRegistTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wn_student.student_regist_time
     *
     * @param studentRegistTime the value for wn_student.student_regist_time
     *
     * @mbg.generated Mon Aug 24 22:56:34 CST 2020
     */
    public void setStudentRegistTime(Date studentRegistTime) {
        this.studentRegistTime = studentRegistTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wn_student.student_school
     *
     * @return the value of wn_student.student_school
     *
     * @mbg.generated Mon Aug 24 22:56:34 CST 2020
     */
    public String getStudentSchool() {
        return studentSchool;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wn_student.student_school
     *
     * @param studentSchool the value for wn_student.student_school
     *
     * @mbg.generated Mon Aug 24 22:56:34 CST 2020
     */
    public void setStudentSchool(String studentSchool) {
        this.studentSchool = studentSchool == null ? null : studentSchool.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wn_student.student_major
     *
     * @return the value of wn_student.student_major
     *
     * @mbg.generated Mon Aug 24 22:56:34 CST 2020
     */
    public String getStudentMajor() {
        return studentMajor;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wn_student.student_major
     *
     * @param studentMajor the value for wn_student.student_major
     *
     * @mbg.generated Mon Aug 24 22:56:34 CST 2020
     */
    public void setStudentMajor(String studentMajor) {
        this.studentMajor = studentMajor == null ? null : studentMajor.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column wn_student.student_graduate_time
     *
     * @return the value of wn_student.student_graduate_time
     *
     * @mbg.generated Mon Aug 24 22:56:34 CST 2020
     */
    public Date getStudentGraduateTime() {
        return studentGraduateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column wn_student.student_graduate_time
     *
     * @param studentGraduateTime the value for wn_student.student_graduate_time
     *
     * @mbg.generated Mon Aug 24 22:56:34 CST 2020
     */
    public void setStudentGraduateTime(Date studentGraduateTime) {
        this.studentGraduateTime = studentGraduateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wn_student
     *
     * @mbg.generated Mon Aug 24 22:56:34 CST 2020
     */
    @Override
    public String toString() {
        StringBuilder sb = new StringBuilder();
        sb.append(getClass().getSimpleName());
        sb.append(" [");
        sb.append("Hash = ").append(hashCode());
        sb.append(", studentId=").append(studentId);
        sb.append(", studentName=").append(studentName);
        sb.append(", studentBirth=").append(studentBirth);
        sb.append(", studentStatus=").append(studentStatus);
        sb.append(", studentRegistTime=").append(studentRegistTime);
        sb.append(", studentSchool=").append(studentSchool);
        sb.append(", studentMajor=").append(studentMajor);
        sb.append(", studentGraduateTime=").append(studentGraduateTime);
        sb.append("]");
        return sb.toString();
    }
}