package com.example.test0821.dao;

import com.example.test0821.entity.Student;
import com.example.test0821.entity.StudentExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface StudentMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wn_student
     *
     * @mbg.generated Mon Aug 24 22:56:34 CST 2020
     */
    long countByExample(StudentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wn_student
     *
     * @mbg.generated Mon Aug 24 22:56:34 CST 2020
     */
    int deleteByExample(StudentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wn_student
     *
     * @mbg.generated Mon Aug 24 22:56:34 CST 2020
     */
    int deleteByPrimaryKey(Integer studentId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wn_student
     *
     * @mbg.generated Mon Aug 24 22:56:34 CST 2020
     */
    int insert(Student record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wn_student
     *
     * @mbg.generated Mon Aug 24 22:56:34 CST 2020
     */
    int insertSelective(Student record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wn_student
     *
     * @mbg.generated Mon Aug 24 22:56:34 CST 2020
     */
    List<Student> selectByExample(StudentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wn_student
     *
     * @mbg.generated Mon Aug 24 22:56:34 CST 2020
     */
    Student selectByPrimaryKey(Integer studentId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wn_student
     *
     * @mbg.generated Mon Aug 24 22:56:34 CST 2020
     */
    int updateByExampleSelective(@Param("record") Student record, @Param("example") StudentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wn_student
     *
     * @mbg.generated Mon Aug 24 22:56:34 CST 2020
     */
    int updateByExample(@Param("record") Student record, @Param("example") StudentExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wn_student
     *
     * @mbg.generated Mon Aug 24 22:56:34 CST 2020
     */
    int updateByPrimaryKeySelective(Student record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table wn_student
     *
     * @mbg.generated Mon Aug 24 22:56:34 CST 2020
     */
    int updateByPrimaryKey(Student record);
}